DATASET:
  root_dataset: "./data/"
  list_val: "./data/skycloud_small.odgt"
  imgSizes: (400, 500, 600, 700)
  imgMaxSize: 1000
  num_attr_class: (4, 4, 4)
  num_seg_class: 2
  num_cloud_class: 2
  padding_constant: 32
  segm_downsampling_rate: 1
  random_flip: True
  random_crop: False
  classInfo: "./data/labels.json"

MODEL:
  arch_encoder: "resnet50"
  fc_dim: 2048

VAL:
  visualize: False
  checkpoint: "epoch_40.pth"
  sky_seg: False
  cloud_seg: True

TEST:
  checkpoint: "epoch_20.pth"
  result: "./test/"

DIR: "weights/"
